# Generated by Django 2.1.7 on 2019-05-06 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifyDate', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('company', models.CharField(max_length=32)),
                ('posotion', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('wechat', models.CharField(max_length=32)),
            ],
        ),
    ]
