# Generated by Django 2.1.7 on 2019-05-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sz_app', '0002_auto_20190508_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
